Repository poanetwork/nifty-wallet, pull requests merged in 2018-10, with the labels that each got.

#150 e2e add token validation
  test/e2e/metamask.spec.js
  test/integration/lib/add-token.js
  test/integration/lib/first-time.js
Labels: in progress

#140 (Feature) Search tokens in POA network
  .circleci/config.yml
  .nvmrc
  gulpfile.js
  old-ui/app/components/add-token/add-token.component.js
  old-ui/app/components/add-token/token-list/token-list.component.js
  old-ui/app/components/add-token/token-search/index.js
  old-ui/app/components/add-token/token-search/token-search.component.js
  old-ui/app/components/add-token/token-search/token-search.container.js
  old-ui/app/components/confirm-add-token/confirm-add-token.component.js
  old-ui/app/components/confirm-add-token/confirm-add-token.container.js
  old-ui/app/components/identicon.js
  old-ui/app/components/token-list.js
  old-ui/lib/icon-factory.js
  package-lock.json
  package.json
  ui/lib/icon-factory.js
Labels: awaiting for review

#142 (Feature) Token menu: view in explorer/copy/remove
  old-ui/app/components/account-dropdowns.js
  old-ui/app/components/token-cell.js
  old-ui/app/components/token-list.js
  old-ui/app/css/index.css
  package-lock.json
  package.json
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: awaiting for review, e2e tests are affected

#151 resolve merge conflict
  test/e2e/metamask.spec.js
Labels: in progress

#149 (Fix) Add custom tokens validation
  old-ui/app/app.js
  old-ui/app/components/add-token/add-token.component.js
  old-ui/app/components/token-cell.js
  old-ui/app/components/token-list.js
  old-ui/app/css/index.css
  old-ui/lib/icon-factory.js
  test/e2e/metamask.spec.js
  test/integration/lib/add-token.js
  test/integration/lib/first-time.js
  test/unit/ui/add-token.spec.js
Labels: awaiting for review, e2e tests are affected

#158 e2e dai fix merging conflict
  test/e2e/metamask.spec.js
Labels: in progress

#153 (Feature) DAI chain support
  app/scripts/controllers/network/enums.js
  app/scripts/controllers/network/network.js
  old-ui/app/app.js
  old-ui/app/components/buy-button-subview.js
  old-ui/app/components/fiat-value.js
  old-ui/app/components/network.js
  old-ui/app/conf-tx.js
  old-ui/app/config.js
  old-ui/app/util.js
  package-lock.json
  package.json
  test/e2e/elements.js
  test/e2e/metamask.spec.js
  ui/app/actions.js
Labels: awaiting for review, e2e tests are affected

#164 (Fix) Retrieving of token's symbol and decimals on transfer
  CHANGELOG.md
  old-ui/app/send-token.js
  package-lock.json
  package.json
  ui/app/token-util.js
Labels: awaiting for review, high priority

#163 fixed test for mm-4.9.3
  test/e2e/elements.js
  test/e2e/metamask.spec.js
  test/integration/lib/first-time.js
Labels: in progress

#168 e2e mm 4.9.3
  package-lock.json
  package.json
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: in progress

#170 tests for mm-4.11.0
  .circleci/config.yml
  app/scripts/lib/personal-message-manager.js
  package-lock.json
  test/base.conf.js
  test/e2e/elements.js
  test/e2e/metamask.spec.js
  test/integration/lib/add-token.js
  test/integration/lib/currency-localization.js
  test/integration/lib/first-time.js
  test/integration/lib/mascara-first-time.js
  test/unit/app/controllers/detect-tokens-test.js
  test/unit/app/controllers/preferences-controller-test.js
Labels: in progress

#171 (Fix) Remove unused deps
  package-lock.json
  package.json
Labels: in progress

#176 e2e tests for autodetect tokens in Mainnet and Poa
  package-lock.json
  test/e2e/metamask.spec.js
Labels: in progress

#173 (Fix) xDai chain fixes
  app/scripts/platforms/extension.js
  old-ui/app/components/transaction-list-item.js
Labels: awaiting for review

#178 e2e tests autodetect tokens in Mainnet
  test/e2e/metamask.spec.js
Labels: in progress
