Repository poanetwork/nifty-wallet, pull requests merged in 2018-12, with the labels that each got.

#211 fix e2e for enhance-rpc-validation branch
  package-lock.json
  package.json
  test/e2e/metamask.spec.js
Labels: in progress

#215 e2e test for import contract feature
  package-lock.json
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: in progress

#216 e2e import contract changed behavior button Import
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: in progress

#218 tests for the button 'Copy ABI encoded'
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: in progress

#209 (Fix) Enhance custom RPC validation
  CHANGELOG.md
  app/manifest.json
  old-ui/app/config.js
  package-lock.json
  package.json
  test/e2e/EIP20.sol
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: awaiting for review

#220 NW Release 4.10.0
  .circleci/config.yml
  CHANGELOG.md
  app/manifest.json
  app/scripts/metamask-controller.js
  old-ui/app/account-detail.js
  old-ui/app/accounts/import/contract.js
  old-ui/app/accounts/import/index.js
  old-ui/app/app.js
  old-ui/app/components/account-dropdowns.js
  old-ui/app/components/add-token/add-token.component.js
  old-ui/app/components/add-token/add-token.container.js
  old-ui/app/components/delete-imported-account.js
  old-ui/app/components/send/choose-contract-executor.js
  old-ui/app/components/send/executor-cell.js
  old-ui/app/components/send/send-contract.js
  old-ui/app/components/send/send-error.js
  old-ui/app/components/send/send-header.js
  old-ui/app/components/send/send-profile.js
  old-ui/app/components/send/send-token.js
  old-ui/app/components/send/send.js
  old-ui/app/config.js
  old-ui/app/css/index.css
  old-ui/app/css/lib.css
  old-ui/app/css/send-contract.css
  old-ui/app/util.js
  old-ui/css.js
  package-lock.json
  package.json
  test/e2e/EIP20.sol
  test/e2e/elements.js
  test/e2e/metamask.spec.js
  test/unit/old-ui/app/components/send/choose-contract-executor.spec.js
  test/unit/old-ui/app/components/send/executor-cell.spec.js
  test/unit/old-ui/app/components/send/send-error.spec.js
  test/unit/old-ui/app/components/send/send-header.spec.js
  test/unit/old-ui/app/components/send/send-profile.spec.js
  test/unit/old-ui/app/util.spec.js
  test/unit/ui/app/actions.spec.js
  ui/app/actions.js
  ui/app/reducers/app.js
  ui/app/select-app.js
Labels: in progress

#221 E2e contract multiply outputs
  package-lock.json
  test/e2e/metamask.spec.js
Labels: in progress

#225 e2e: test different types of outputs for feature 'Ecxecute method'
  test/e2e/elements.js
  test/e2e/func.js
  test/e2e/metamask.spec.js
Labels: in progress

#230 e2e drop down menu for boolean function
  test/e2e/func.js
  test/e2e/metamask.spec.js
Labels: in progress

#231 e2e issue#227
  .circleci/config.yml
  test/e2e/func.js
Labels: in progress

#219 (Feature) Multiple outputs fields for contract calls
  old-ui/app/components/send/send-contract.js
  package-lock.json
  test/e2e/elements.js
  test/e2e/metamask.spec.js
  test/unit/old-ui/app/util.spec.js
Labels: awaiting for review, e2e tests are affected

#228 Update npm packages versions
  package-lock.json
  package.json
Labels: awaiting for review

#235 e2e check clipboard
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: in progress

#236 e2e execute button
  package-lock.json
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: in progress

#224 (Fix) Bytes is not a mandatory input
  old-ui/app/components/send/send-contract.js
Labels: awaiting for review

#226 (Feature) Label for hardware acc
  old-ui/app/components/account-dropdowns.js
Labels: awaiting for review

#232 (Fix) Execute methods button
  old-ui/app/account-detail.js
  package-lock.json
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: awaiting for review, e2e tests are affected

#233 (Feature) Copy contract ABI from menu
  old-ui/app/components/account-dropdowns.js
  package-lock.json
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: awaiting for review

#229 (Feature) Select input for Boolean type for contract type acc
  old-ui/app/components/send/send-contract.js
  test/e2e/func.js
  test/e2e/metamask.spec.js
Labels: awaiting for review, e2e tests are affected

#240 e2e for change-to-contract-acc-after-execution
  package-lock.json
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: in progress

#241 (Fix) Downgrade HD related packages versions for release
  package-lock.json
  package.json
Labels: awaiting for review

#242 e2e contract-executor-reorder
  old-ui/app/components/buy-button-subview.js
  old-ui/app/components/send/choose-contract-executor.js
  old-ui/app/conf-tx.js
  package-lock.json
  test/e2e/elements.js
  test/e2e/metamask.spec.js
  test/unit/ui/app/actions.spec.js
  ui/app/actions.js
  ui/app/reducers/app.js
Labels: in progress

#243 e2e connect hd wallet
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: in progress

#244 NW release 4.10.1
  .circleci/config.yml
  CHANGELOG.md
  app/manifest.json
  old-ui/app/account-detail.js
  old-ui/app/components/account-dropdowns.js
  old-ui/app/components/buy-button-subview.js
  old-ui/app/components/send/choose-contract-executor.js
  old-ui/app/components/send/send-contract.js
  old-ui/app/conf-tx.js
  package-lock.json
  package.json
  test/e2e/elements.js
  test/e2e/func.js
  test/e2e/metamask.spec.js
  test/unit/old-ui/app/components/send/choose-contract-executor.spec.js
  test/unit/old-ui/app/util.spec.js
  test/unit/ui/app/actions.spec.js
  ui/app/actions.js
  ui/app/reducers/app.js
Labels: in progress
