Repository poanetwork/nifty-wallet, pull requests merged in 2018-11, with the labels that each got.

#177 (Fix) Zero balance display instead of "None"
  old-ui/app/util.js
  package-lock.json
Labels: awaiting for review

#179 e2e send messages
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: in progress

#174 (Fix) Sign data and recover account pages styles fixes
  old-ui/app/app.js
  old-ui/app/components/account-panel.js
  old-ui/app/components/binary-renderer.js
  old-ui/app/components/pending-msg-details.js
  old-ui/app/components/pending-msg.js
  old-ui/app/components/pending-personal-msg-details.js
  old-ui/app/components/pending-personal-msg.js
  old-ui/app/components/pending-typed-msg-details.js
  old-ui/app/components/pending-typed-msg.js
  old-ui/app/components/typed-message-renderer.js
  old-ui/app/conf-tx.js
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: awaiting for review

#175 (Feature) auto-detect tokens for POA
  app/scripts/controllers/detect-tokens.js
  app/scripts/metamask-controller.js
  package-lock.json
  test/e2e/metamask.spec.js
Labels: awaiting for review

#182 (Refactoring) Generalizing of retrieving of faucets/exchanges links
  app/popup.html
  app/scripts/lib/buy-eth-url.js
  app/scripts/metamask-controller.js
  old-ui/app/components/buy-button-subview.js
  old-ui/app/components/coinbase-form.js
  old-ui/app/css/index.css
  package-lock.json
  package.json
  test/unit/app/buy-eth-url.spec.js
  ui/app/actions.js
Labels: awaiting for review

#186 (Fix) Remove MM warning and fix white pending tx page
  app/scripts/inpage.js
  old-ui/app/components/pending-tx.js
Labels: awaiting for review, high priority, logical bug

#188 (Update) release URI
  development/publish-release.js
Labels: in progress

#191 (Fix) Handle: Cannot read property address of undefined
  app/scripts/controllers/token-rates.js
Labels: awaiting for review

#190 (Fix) Display non-zero fiat value
  old-ui/app/components/fiat-value.js
  old-ui/app/util.js
  package-lock.json
  package.json
  test/unit/old-ui/app/components/fiat-value.spec.js
  test/unit/old-ui/app/util.spec.js
Labels: awaiting for review

#192 (Update) eth-token-watcher dependency (upstream from parent repo)
  package-lock.json
  package.json
Labels: awaiting for review

#200 e2e doubled fired events
  package-lock.json
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: in progress

#199 (Fix) Doubled fired events
  package-lock.json
  package.json
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: awaiting for review

#201 (Fix) Update texts descriptions
  app/_locales/en/messages.json
  app/_locales/fr/messages.json
  app/_locales/hn/messages.json
  app/_locales/ht/messages.json
  app/_locales/it/messages.json
  app/_locales/ja/messages.json
  app/_locales/pl/messages.json
  app/_locales/tr/messages.json
  app/scripts/controllers/detect-tokens.js
  app/scripts/inpage.js
  app/scripts/lib/message-manager.js
  app/scripts/lib/typed-message-manager.js
  package-lock.json
Labels: awaiting for review

#202 (Fix) Detect tokens: handle undefined tokenAddresses
  app/scripts/controllers/detect-tokens.js
Labels: awaiting for review

#203 (Fix) Handle undefined txParams
  app/scripts/controllers/transactions/index.js
Labels: awaiting for review

#205 (Feature) Hide export private key option for HD wallet
  old-ui/app/account-detail.js
  old-ui/app/components/account-dropdowns.js
Labels: awaiting for review

#207 (Fix) Format of token balance in the tokens list
  old-ui/app/components/token-cell.js
Labels: awaiting for review

#210 e2e improve stability
  test/e2e/EIP20.sol
  test/e2e/elements.js
  test/e2e/metamask.spec.js
Labels: in progress
